# env.nu — Environment variables, PATH, and prompt init
# Location: ~/.config/nushell/env.nu
#
# Loaded before config.nu. Responsible for everything that must be visible
# to all processes spawned from this shell.
#
# ── Home-manager note ────────────────────────────────────────────────────────
# If Nushell is managed by home-manager, this file may be generated and
# marked read-only. In that case, do not edit this file directly. Instead,
# place this content in your home-manager configuration:
#
#   programs.nushell.extraEnv = builtins.readFile ./env.nu;
#
# or inline it as a string under `programs.nushell.environmentVariables`
# and `programs.nushell.extraEnv`.
# ─────────────────────────────────────────────────────────────────────────────

# ============================================================================
# XDG Base Directory Specification
# ============================================================================
$env.XDG_CONFIG_HOME = ($env.HOME | path join ".config")
$env.XDG_DATA_HOME   = ($env.HOME | path join ".local" "share")
$env.XDG_STATE_HOME  = ($env.HOME | path join ".local" "state")
$env.XDG_CACHE_HOME  = ($env.HOME | path join ".cache")

# ============================================================================
# Editor
# ============================================================================
$env.EDITOR = "nvim"
$env.VISUAL  = "nvim"

# ============================================================================
# Starship config path
# ============================================================================
$env.STARSHIP_CONFIG = ($env.HOME | path join ".config" "starship" "starship.toml")

# ============================================================================
# Tool environment variables
# Set unconditionally where safe; guarded by path exists where the tool
# directory may not exist on all machines.
# ============================================================================
$env.NPM_CONFIG_PREFIX = ($env.HOME | path join ".npm-packages")

if ($env.HOME | path join ".bun" | path exists) {
    $env.BUN_INSTALL = ($env.HOME | path join ".bun")
}

if ($env.HOME | path join "go" | path exists) {
    $env.GOPATH = ($env.HOME | path join "go")
    $env.GOBIN  = ($env.HOME | path join "go" "bin")
}

if ($env.HOME | path join ".pyenv" | path exists) {
    $env.PYENV_ROOT = ($env.HOME | path join ".pyenv")
}

# ============================================================================
# PATH — Phase 1: personal and tool candidates
#
# All candidate directories are listed, filtered to those that exist, then
# prepended to the inherited PATH in a single assignment. The ^ prefix on
# path exists is not needed — path exists is a Nu builtin, not an external.
# ============================================================================
let personal_bins = (
    [
        # Personal
        ($env.HOME | path join ".local"          "bin")
        # Language runtimes
        ($env.HOME | path join ".cargo"          "bin")
        ($env.HOME | path join ".bun"            "bin")
        ($env.HOME | path join ".deno"           "bin")
        ($env.HOME | path join ".npm-packages"   "bin")
        ($env.HOME | path join "go"              "bin")
        # Version managers — shims first so they intercept bare invocations
        ($env.HOME | path join ".pyenv"          "shims")
        ($env.HOME | path join ".pyenv"          "bin")
        ($env.HOME | path join ".rbenv"          "shims")
        # gcloud SDK
        ($env.HOME | path join "google-cloud-sdk" "bin")
        # Nix — hardcoded fallback candidates (superseded by Phase 2 if
        # $NIX_PROFILES is set, but kept for environments where it is not)
        ($env.HOME | path join ".nix-profile"    "bin")
        ($env.HOME | path join ".local" "state" "nix" "profiles" "profile" "bin")
        "/nix/var/nix/profiles/default/bin"
        "/run/current-system/sw/bin"
    ]
    | where { |p| $p | path exists }
)

# ============================================================================
# PATH — Phase 2: $NIX_PROFILES (authoritative for active Nix profile stacks)
#
# On NixOS, home-manager, and multi-profile Nix setups, $NIX_PROFILES
# contains a space-separated list of all active Nix profiles in priority
# order. Iterating over it is more robust than hardcoded paths because it
# automatically covers system + user + home-manager profile combinations.
# ============================================================================
let nix_bins = if "NIX_PROFILES" in $env {
    $env.NIX_PROFILES
    | split row " "
    | each { |p| $p | str trim }
    | where { |p| $p != "" }
    | each { |p| $p | path join "bin" }
    | where { |p| $p | path exists }
} else {
    []
}

$env.PATH = (
    $personal_bins
    | append $nix_bins
    | append $env.PATH
    | uniq
)

# ============================================================================
# LOCALE_ARCHIVE (NixOS / Linux only)
#
# On NixOS, locale data lives in the Nix store rather than /usr/lib/locale.
# Without LOCALE_ARCHIVE, tools like date, grep, and Python emit locale
# warnings. home-manager sets this automatically; standalone Nix does not.
# We detect the presence of NIX_PROFILES on Linux and locate the archive.
# ============================================================================
if "NIX_PROFILES" in $env and $nu.os-info.name == "linux" {
    let locale_archives = (glob "/nix/store/*-glibc-locales-*/lib/locale/locale-archive")
    if ($locale_archives | is-not-empty) {
        $env.LOCALE_ARCHIVE = ($locale_archives | first)
    }
}

# ============================================================================
# Starship prompt init
#
# Must live in env.nu — Nu sets PROMPT_COMMAND from env.nu before
# config.nu is evaluated. PATH is fully constructed above so `which`
# is reliable here.
# ============================================================================
if (which starship | is-not-empty) {
    $env.STARSHIP_SHELL             = "nu"
    $env.PROMPT_COMMAND             = {|| starship prompt }
    $env.PROMPT_COMMAND_RIGHT       = {|| starship prompt --right }
    $env.PROMPT_INDICATOR           = {|| "" }
    $env.PROMPT_INDICATOR_VI_INSERT = {|| ": " }
    $env.PROMPT_INDICATOR_VI_NORMAL = {|| "〉" }
    $env.PROMPT_MULTILINE_INDICATOR = {|| "::: " }
}
