export HISTCONTROL=erasedups
export LESS="-CQaixr4"
export CC=$(which clang)
export CXX=$(which clang++)
export SDKMAN_DIR="$HOME/.sdkman"
export ANACONDA3=/opt/anaconda3
export LINUXBREW=$HOME/.linuxbrew
export MONO_GAC_PREFIX=$LINUXBREW
export XDG_DATA_DIRS="$HOME/.linuxbrew/share:$XDG_DATA_DIRS"
export PATH=$HOME/.local:$HOME/bin:$ANACONDA3/bin:$LINUXBREW/bin:$PATH
export MANPATH=$HOME/.linuxbrew/share/man:$MANPATH
export INFOPATH=$HOME/.linuxbrew/share/info:$INFOPATH
