export CONDA_AUTO_ACTIVATE_BASE=false
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export HISTCONTROL=erasedups
export LESS="-CQaixr4"
export DOTFILES="$HOME/Dotfiles"
export FZF_DEFAULT_COMMAND="fd --type f"
export VIMCONFIG="$HOME/.vim"
export VIMDATA="$HOME/.vim"
export CURL_BIN=/usr/local/opt/curl/bin
export OPENSSL_BIN=/usr/local/opt/openssl/bin
export SDKMAN_DIR="$HOME/.sdkman"
export GOROOT="$(/usr/local/bin/brew --prefix go)/libexec"
export GOPATH="$HOME/Workspace/go"
export ANDROID_SDK_ROOT=/usr/local/share/android-sdk
export FLUTTER_HOME=/usr/local/share/flutter
export CARGO_HOME="$HOME/.cargo"
export PUB_CACHE="$HOME/.pub-cache"
export PATH="$HOME/.local/bin:$PUB_CACHE/bin:$HOME/local/bin:$HOME/bin:$OPENSSL_BIN:$CURL_BIN:/usr/local/bin:/usr/local/sbin:$VIMCONFIG/pack/bundle/start/fzf/bin:$GOROOT/bin:$GOPATH/bin:$ANDROID_SDK_ROOT/build-tools:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$FLUTTER_HOME/bin:$CARGO_HOME/bin:$PATH"
