export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export HISTCONTROL=erasedups
export LESS="-CQaixr4"
export DOTFILES="$HOME/Dotfiles"
export VIMCONFIG="$HOME/.vim"
export VIMDATA="$HOME/.vim"
# export CC=$(which clang)
# export CXX=$(which clang++)
export SDKMAN_DIR="$HOME/.sdkman"
export NVM_HOME="$HOME/.nvm"
export GOROOT="$(/usr/local/bin/brew --prefix go)/libexec"
export GOPATH="$HOME/Workspace/go"
export PATH="$HOME/.local/bin:$HOME/local/bin:$HOME/bin:/usr/local/bin:/usr/local/opt/openssl/bin:$VIMCONFIG/pack/bundle/start/fzf/bin:$GOROOT/bin:$GOPATH/bin:$PATH"
