{ pkgs, ... }: {
  environment.systemPackages = (with pkgs; [
    # --- Stable Packages ---
    babashka
    bat
    cargo
    chafa
    clippy
    clojure
    cljstyle
    coreutils-full
    cq
    delta
    efm-langserver
    fd
    file
    font-awesome
    gcc
    git
    git-lfs
    glow
    golangci-lint-langserver
    google-cloud-sdk
    hadolint
    httpie
    htop
    k3d
    kind
    lua51Packages.lua
    lua51Packages.luarocks
    marksman
    moreutils
    nixpkgs-fmt
    nodejs_22
    prettierd
    powerline-fonts
    R
    ranger
    ripgrep
    rustc
    rustfmt
    shellcheck
    shfmt
    starship
    stow
    stylua
    sqlfluff
    taplo
    temurin-bin
    tilt
    tmux
    tree
    ueberzugpp
    viu
    vscode-json-languageserver
    yaml-language-server
    yamllint
    zprint
  ]) ++ (with pkgs.unstable; [
    # --- Unstable Packages (via Overlay) ---
    biome
    bruno
    bruno-cli
    bun
    carapace
    claude-code
    clojure-lsp
    cmake
    dbeaver-bin
    deno
    direnv
    emacs
    eza
    fzf
    gemini-cli
    gettext
    hoppscotch
    jq
    kitty
    ktlint
    kotlin
    kotlin-interactive-shell
    kotlin-language-server
    kubectl
    lazygit
    libtool
    llama-cpp
    lua-language-server
    neovim
    nushell
    nil
    ollama
    opencode
    pandoc
    pandoc-lua-filters
    pandoc-plantuml-filter
    podman
    podman-tui
    rlwrap
    rio
    sbcl
    sqlite
    sqlit-tui
    texliveSmall
    tree-sitter
    thunderbird
    vscode
    wezterm
  ]);

  fonts.packages = with pkgs; [
    nerd-fonts.iosevka
    nerd-fonts.jetbrains-mono
    nerd-fonts.symbols-only
    nerd-fonts.victor-mono
  ];
}
