local opt = vim.opt

opt.backup = false
opt.clipboard = 'unnamedplus'
opt.confirm = true
opt.expandtab = true
opt.fillchars = 'eob: '
opt.ignorecase = true
opt.listchars = 'tab:▸ ,trail:·'
opt.list = true
opt.mouse = 'a'
opt.number = true
opt.redrawtime = 10000
opt.relativenumber = true
opt.scrolloff = 5
opt.shiftwidth = 4
opt.showmode = false
opt.sidescrolloff = 5
opt.signcolumn = 'yes:2'
opt.smartcase = true
opt.spell = true
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 2
opt.termguicolors = true
opt.title = true
opt.undofile = true
opt.updatetime = 250
opt.wildmode = 'longest:full,full'
opt.wrap = false
