#!/usr/bin/env bash

IFS='' read -d '' icon <<- HERE
					  ......:::::::::::::----
					 .=====================-
					 =====================-
					-====================-
				   :====================-
				  .====================-
				  ====================-
				 -===================-
				:===================-
			   .------==============--------
					 -====================-
					.====================-
					====================-
				   :===================:
				  .===================.
				  -==================.
				 :==================:....
				 ======================:
				 ....-===============:
					 ==============-.
					.=============.
					-===========:
				   .==========-
				   -========-.
				   ========:
				  :======-
				  -====-.
				 .====:
				 -==:
				 =-
				:.
HERE

printf "%s\n" "$icon"

read -p 'Shazam?! [y|n] ' confirmation

function log {
	local status=$1
	local msg=$2

	case "$status" in
		[Cc]ompletion)
			printf "%b %s\n" "\xe2\x9c\x85" "$msg"
		;;
		[Ee]rror)
			printf "%b %s\n" "\xe2\x9d\x8c" "$msg"
		;;
		*)
			printf "%b %s\n" "\xe2\x9a\xa1" "$msg"
		;;		  
	esac
}

function err {
	log "error" "Unable to complete setup; please retry."
	exit
}

function install_nix {
	log "progress" "Installing Nix package manager."
	
	os=$(uname -s)
	
	case "$os" in
		Darwin*)
			sh <(curl -L https://nixos.org/nix/install)
		;;
		Linux*)
			sh <(curl -L https://nixos.org/nix/install) --daemon
		;;
	esac

	log "completion" "Installed Nix package manager."
}

function install_home_manager {
	log "progress" "Installing Home Manager."

	. /etc/bashrc

	nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
	nix-channel --update
	nix-shell '<home-manager>' -A install
	nix build --extra-experimental-features "nix-command flakes" --impure --no-link $dotfiles_dir/nixpkgs/.config/nixpkgs#homeConfigurations."$USER".activationPackage
	"$(nix path-info ${dotfiles_dir}/nixpkgs/.config/nixpkgs#homeConfigurations.${USER}.activationPackage)"/activate
	home-manager --extra-experimental-features "nix-command flakes" --impure switch --flake $dotfiles_dir/nixpkgs/.config/nixpkgs#"$USER"

	log "completion" "Installed Home Manager."
}

function link_targets {
	cd $dotfiles_dir

	targets=(alacritty clojure emacs git lazygit neovim nix tmux)

	log "progress" "Stowing targets."

	for target in ${targets[@]}
	do
		stow --verbose --target "$HOME" --stow "$target"
	done

	log "completion" "Stowed Targets."
}

function update_shells {
	log "progress" "Updating '/etc/shells'."

	printf "$HOME/.nix-profile/bin/fish\n" | sudo tee -a /etc/shells > /dev/null

	log "completion" "Updated '/etc/shells'."
}

function change_shell {
	log "progress" "Changing default shell."

	chsh -s "$HOME/.nix-profile/bin/fish"

	log "completion" "Changed default shell."
}

trap "err" 1 2 3 6

case $confirmation in
	[Yy]*)
	scripts_dir="$(dirname "$(readlink -f "$0")")"
	dotfiles_dir="${scripts_dir%/shell/scripts}"
	#install_nix
	install_home_manager
	link_targets
	update_shells
	change_shell
	exit 0
	;;
	[Nn]*)
	printf 'Goodbye!...\n'
	exit 0
	;;
esac
