#!/usr/bin/env bash

IFS='' read -d '' icon <<- HERE
                      ......:::::::::::::----
                     .=====================-
                     =====================-
                    -====================-
                   :====================-
                  .====================-
                  ====================-
                 -===================-
                :===================-
               .------==============--------
                     -====================-
                    .====================-
                    ====================-
                   :===================:
                  .===================.
                  -==================.
                 :==================:....
                 ======================:
                 ....-===============:
                     ==============-.
                    .=============.
                    -===========:
                   .==========-
                   -========-.
                   ========:
                  :======-
                  -====-.
                 .====:
                 -==:
                 =-
                :.
HERE

printf "%s\n" "$icon"

read -p 'Shazam?! [y|n] ' confirmation

function log {
    local status=$1
    local msg=$2

    case "$status" in
        [C|c]ompletion)
            printf "%b %s\n" "\xe2\x9c\x85" "$msg"
        ;;
        *)
            printf "%b %s\n" "\xe2\x9a\xa1" "$msg"
        ;;        
    esac
}

function link_targets {
    cd "${"$(dirname "$(readlink -f "$0")")"%shell}"

    targets=(git neovim nix tmux)

    log "progress" "Stowing targets."

    for target in ${targets[@]}
    do
        stow --verbose --target="$HOME" --stow "$target"
    done

    log "completion" "Targets stowed."
}

function install_nix {
    log "progress" "Installing Nix package manager."
    
    os=$(uname -s)
    
    case "$os" in
        Darwin*)
            sh <(curl -L https://nixos.org/nix/install)
        ;;
        Linux*)
            sh <(curl -L https://nixos.org/nix/install) --daemon
        ;;
    esac

    log "completion" "Nix package manager installed."
}

function update_shells {
    log "progress" "Updating '/etc/shells'."

    printf "$HOME/.nix-profile/bin/fish" | sudo tee -a /etc/shells

    log "completion" "Updated '/etc/shells'."
}

function change_shell {
    log "progress" "Changing default shell."

    chsh -s "$HOME/.nix-profile/bin/fish"

    log "completion" "Changed default shell."
}

case $confirmation in
    [Yy]*)
    link_targets
    install_nix
    update_shells
    change_shell
    ;;
    [Nn]*)
    printf 'Goodbye!...\n'
    exit 0
    ;;
esac
