#!/usr/bin/env bash

code --install-extension ahmadawais.shades-of-purple
code --install-extension auiworks.amvim
code --install-extension betterthantomorrow.calva
code --install-extension castwide.solargraph
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension connorshea.vscode-ruby-test-adapter
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension eamodio.gitlens
code --install-extension hbenl.vscode-test-explorer
code --install-extension iocave.monkey-patch
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension kaiwood.endwise
code --install-extension mauricioszabo.clover
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.test-adapter-converter
code --install-extension nwolverson.ide-purescript
code --install-extension nwolverson.language-purescript
code --install-extension PKief.material-icon-theme
code --install-extension rebornix.ruby
code --install-extension redhat.vscode-yaml
code --install-extension RobbOwen.synthwave-vscode
code --install-extension svelte.svelte-vscode
code --install-extension tinkertrain.theme-panda
code --install-extension usernamehw.errorlens
code --install-extension wingrunr21.vscode-ruby
