[general]
avatar_image = "/home/danish/Pictures/Avatars/dan_sheikh.png"
radius_ratio = 0.25

[theme]
mode = "dark"
source = "builtin"
builtin = "Catppuccin"

[location]
name = "Newburyport, MA"
month_before_day = true

[bar.main]
position = "top"
bar_type = "simple"
density = "comfortable"
background_opacity = 0.85
show_capsule = true

start = [
  "control-center",
  "network",
  "bluetooth"
]

center = [
  "workspaces"
]

end = [
  "taskbar",
  "volume",
  "brightness",
  "battery",
  "clock",
  "notifications",
  "tray"
]

[widget.workspaces]
display = "none"
hide_when_empty = true

[widget.control-center]
glyph = "brand-arch"

[widget.battery]
always_show_percentage = false
warning_threshold = 20

[widget.clock]
format = "%H:%M"
vertical_format = "%H %M"
use_monospaced_font = true

[widget.notifications]
hide_when_no_unread = false

[wallpaper]
wallpapers_folder = "/home/danish/Pictures/Wallpapers"
enable_overview_wallpaper = true
order = "random"
change_interval = 1800

[wallpaper.default]
path = "/home/danish/Pictures/Wallpapers/galaxy.jpg"

[idle]
enabled = false
screen_off_timeout = 300
lock_timeout = 360
suspend_timeout = 1800
