#!/usr/bin/env bash

extensions=(adrianwilczynski.alpine-js-intellisense
            asciidoctor.asciidoctor-vscode
            betterthantomorrow.calva
            betterthantomorrow.calva-spritz
            bradlc.vscode-tailwindcss
            catppuccin.catppuccin-vsc
            catppuccin.catppuccin-vsc-icons
            charliermarsh.ruff
            davidanson.vscode-markdownlint
            dbaeumer.vscode-eslint
            denoland.vscode-deno
            djblue.portal
            donjayamanne.githistory
            eamodio.gitlens
            editorconfig.editorconfig
            esbenp.prettier-vscode
            firefox-devtools.vscode-firefox-debug
            golang.go
            hashicorp.hcl
            hashicorp.terraform
            hbenl.vscode-test-explorer
            ionide.ionide-fake
            ionide.ionide-fsharp
            ionide.ionide-paket
            ionide.mechanic
            lightbend.vscode-sbt-scala
            mrmlnc.vscode-duplicate
            ms-azuretools.vscode-docker
            ms-dotnettools.csdevkit
            ms-dotnettools.csharp
            ms-dotnettools.dotnet-interactive-vscode
            ms-dotnettools.vscode-dotnet-runtime
            ms-edgedevtools.vscode-edge-devtools
            ms-kubernetes-tools.vscode-kubernetes-tools
            ms-python.debugpy
            ms-python.isort
            ms-python.python
            ms-python.vscode-pylance
            ms-toolsai.jupyter
            ms-toolsai.jupyter-keymap
            ms-toolsai.jupyter-renderers
            ms-toolsai.vscode-jupyter-cell-tags
            ms-toolsai.vscode-jupyter-slideshow
            ms-vscode-remote.remote-containers
            ms-vscode-remote.remote-ssh
            ms-vscode-remote.remote-ssh-edit
            ms-vscode-remote.remote-wsl
            ms-vscode-remote.vscode-remote-extensionpack
            ms-vscode.makefile-tools
            ms-vscode.powershell
            ms-vscode.remote-explorer
            ms-vscode.remote-server
            ms-vscode.test-adapter-converter
            msjsdiag.vscode-react-native
            nomicfoundation.hardhat-solidity
            nwolverson.ide-purescript
            nwolverson.language-purescript
            pkief.material-icon-theme
            pkief.material-product-icons
            quarto.quarto
            rebornix.toggle
            redhat.vscode-yaml
            reditorsupport.r
            samuelcolvin.jinjahtml
            scala-lang.scala
            scalameta.metals
            usernamehw.errorlens
            visualstudioexptteam.intellicode-api-usage-examples
            visualstudioexptteam.vscodeintellicode
            vscodevim.vim
            wayou.vscode-todo-highlight
            wix.vscode-import-cost
            yzhang.markdown-all-in-one)

for extension in ${extensions[@]}
do
  code --force --install-extension $extension
done
