#!/usr/bin/env bash

code --install-extension ahmadawais.shades-of-purple
code --install-extension auiworks.amvim
code --install-extension betterthantomorrow.calva
code --install-extension castwide.solargraph
code --install-extension connorshea.vscode-ruby-test-adapter
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension iocave.customize-ui
code --install-extension iocave.monkey-patch
code --install-extension Ionide.Ionide-FAKE
code --install-extension Ionide.Ionide-fsharp
code --install-extension Ionide.Ionide-Paket
code --install-extension Ionide.mechanic
code --install-extension JakeBecker.elixir-ls
code --install-extension jeroen-meijer.pubspec-assist
code --install-extension kaiwood.endwise
code --install-extension mauricioszabo.clover
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.test-adapter-converter
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension nwolverson.ide-purescript
code --install-extension nwolverson.language-purescript
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension PKief.material-product-icons
code --install-extension rebornix.ruby
code --install-extension rebornix.toggle
code --install-extension redhat.vscode-yaml
code --install-extension RobbOwen.synthwave-vscode
code --install-extension rust-lang.rust
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension svelte.svelte-vscode
code --install-extension tinkertrain.theme-panda
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wingrunr21.vscode-ruby
