code --install-extension adrianwilczynski.alpine-js-intellisense
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension betterthantomorrow.calva
code --install-extension betterthantomorrow.calva-spritz
code --install-extension bradlc.vscode-tailwindcss
code --install-extension catppuccin.catppuccin-vsc
code --install-extension catppuccin.catppuccin-vsc-icons
code --install-extension charliermarsh.ruff
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension djblue.portal
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension golang.go
code --install-extension hashicorp.hcl
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension ionide.ionide-fake
code --install-extension ionide.ionide-fsharp
code --install-extension ionide.ionide-paket
code --install-extension ionide.mechanic
code --install-extension lightbend.vscode-sbt-scala
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.dotnet-interactive-vscode
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension msjsdiag.vscode-react-native
code --install-extension nomicfoundation.hardhat-solidity
code --install-extension nwolverson.ide-purescript
code --install-extension nwolverson.language-purescript
code --install-extension pkief.material-icon-theme
code --install-extension pkief.material-product-icons
code --install-extension quarto.quarto
code --install-extension rebornix.toggle
code --install-extension redhat.vscode-yaml
code --install-extension reditorsupport.r
code --install-extension samuelcolvin.jinjahtml
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension yzhang.markdown-all-in-one
