local utility = require('lib.utility')

utility.map('i', '<C-c>', '<esc><C-w>c')
utility.map('i', '<C-h>', '<esc><C-w>h')
utility.map('i', '<C-j>', '<esc><C-w>j')
utility.map('i', '<C-k>', '<esc><C-w>k')
utility.map('i', '<C-l>', '<esc><C-w>l')
utility.map('i', '<C-o>', '<esc><C-w>o')

utility.map('n', '<C-c>', '<C-w>c')
utility.map('n', '<C-h>', '<cmd>TmuxNavigateLeft<cr>')
utility.map('n', '<C-j>', '<cmd>TmuxNavigateDown<cr>')
utility.map('n', '<C-k>', '<cmd>TmuxNavigateUp<cr>')
utility.map('n', '<C-l>', '<cmd>TmuxNavigateRight<cr>')

utility.map('n', '<C-o>', '<C-w>o')
utility.map('n', '<C-s>', '<C-w>v')
utility.map('n', '<C-S>', '<C-w>s')
utility.map('n', '+', '<C-w>+')
utility.map('n', '-', '<C-w>-')
utility.map('n', ']', '<C-w>>')
utility.map('n', '[', '<C-w><')
utility.map('n', '_', '<C-w>_')
utility.map('n', '<bar>', '<C-w>|')
utility.map('n', '<M-j>', '<cmd>bprevious<cr>')
utility.map('n', '<M-k>', '<cmd>bnext<cr>')
utility.map('n', '<C-S-tab>', '<cmd>bprevious<cr>')
utility.map('n', '<C-tab>', '<cmd>bnext<cr>')

utility.map('n', '<leader>n', '<cmd>enew<cr>')
utility.map('n', '<leader>ml', '<cmd>FloatermNew lazygit<cr>')
utility.map('n', '<leader>mr', '<cmd>FloatermNew ranger<cr>')
utility.map('n', '<leader>mt', '<cmd>FloatermToggle<cr>')
utility.map('n', '<leader>b', '<cmd>FzfLua buffers<cr>')
utility.map('n', '<leader>d', '<cmd>FzfLua diagnostics_document<cr>')
utility.map('n', '<leader>f', '<cmd>FzfLua files<cr>')
utility.map('n', '<leader>g', '<cmd>FzfLua live_grep<cr>')
utility.map('n', '<leader>l', '<cmd>FzfLua treesitter<cr>')
utility.map('n', '<leader>s', '<cmd>lua vim.lsp.buf.format({ async = false })<cr>')
-- utility.map('n', '<leader>b', '<cmd>Telescope buffers<cr>')
-- utility.map('n', '<leader>d', '<cmd>Telescope diagnostics<cr>')
-- utility.map('n', '<leader>e', '<cmd>Telescope file_browser<cr>')
-- utility.map('n', '<leader>f', '<cmd>Telescope find_files<cr>')
-- utility.map('n', '<leader>g', '<cmd>Telescope live_grep<cr>')
-- utility.map('n', '<leader>l', '<cmd>Telescope treesitter<cr>')
utility.map('n', '<leader>o', '<cmd>Oil<cr>')

utility.map('v', ';', '<cmd>')
