;;; evil-embrace-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from evil-embrace.el

(autoload 'evil-embrace-enable-evil-surround-integration "evil-embrace" nil t)
(autoload 'evil-embrace-disable-evil-surround-integration "evil-embrace" nil t)
(register-definition-prefixes "evil-embrace" '("evil-embrace-"))

;;; End of scraped data

(provide 'evil-embrace-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; evil-embrace-autoloads.el ends here
