lastupdatecheck: 0
recentrepos:
    - /home/danish/dotfiles
startuppopupversion: 5
didshowhunkstaginghint: false
lastversion: 0.60.0
customcommandshistory:
    - git push --force-with-lease origin feature/evp-cdmo
    - git push -f origin feature/evp-cdmo
    - git push -fu origin main
    - git push -u origin main
    - git push origin :refs/tags/v0.1.0-alpha
hidecommandlog: false
